<?php
include "include/header.php";
include "include/leftbar.php";
?>
<div class="page_title">. : : Privacy Policy : : .</div>
<h3>Disclaimer:</h3>
  <p><b>Last revised: JUNE 19, 2013</b></p>
<ol class="privacy">
	<li>The owner of Shobdo-Online.com Web Portal is NOT liable to you for damages, including any general, special, incidental or consequential damages arising by browsing the website, using the information posted on the website and/or clicking the external links.</li>
	<li>The majority of the contents in the Shobdo-Online.com Web Portal are links to external websites. However,   Shobdo-Online.com Web Portal is not affiliated with any other website. Therefore, the owner of this website NEITHER takes any responsibility NOR endorses the contents of external hyperlinks on this website.</li>
	<li>General. You understand that all information, data, text, software, photographs, graphics, video, messages, tags, or other materials (&quot;Content&quot;), whether publicly posted or privately transmitted via the web links we have posted on our site, are the sole responsibility of the person from whom such Content originated. This means that the person who posted the links of the particular Content, and not Shobdo-Online.com, are entirely responsible for all Content that the person upload, post, email, transmit or otherwise make available via the web links we have posted on our site. Shobdo-Online.com does not control the Content posted via the web links we have posted on our site and, as such, does not guarantee the accuracy, integrity or quality of such Content. You understand that by using the web links we have posted on our site, you may be exposed to Content that is offensive, indecent or objectionable. Under no circumstances will Shobdo-Online.com be liable in any way for any Content, including, but not limited to, any errors or omissions in any Content, or any loss or damage of any kind incurred as a result of the use of any Content posted, emailed, transmitted or otherwise made available via the web links we have posted on our site. Shobdo-Online.com does not allow you to upload or download any Content files from or to the Shobdo-Online.com site.</li>
	<li>The Service may provide, or third parties may provide, links to other sites or content (&quot;Third Party Sites&quot;). Because Shobdo-Online.com has no control over Third Party Sites, you acknowledge and agree that Shobdo-Online.com is not responsible for the availability of such external sites or resources, and does not endorse and expressly disclaims responsibility or liability for any information, data, text, software, photographs, graphics, video, messages, tags, or other materials (&quot;Content&quot;), content, advertising, products or other materials on or available from Third Party Sites. You further acknowledge and agree that Shobdo-Online.com shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such information, data, text, software, photographs, graphics, video, messages, tags, or other materials (&quot;Content&quot;), content, goods or services available on or through any Third Party Site. ACCESS AND USE OF THIRD PARTY SITES, INCLUDING THE INFORMATION, MATERIAL, PRODUCTS, AND SERVICES ON THIRD PARTY SITES OR AVAILABLE THROUGH THIRD PARTY SITES, IS SOLELY AT YOUR OWN RISK. You should review applicable terms and policies, including the privacy and data gathering practices, of any Third Party Sites.</li>
	<li>Information posted on this website is without any warranty that it is always correct. Therefore, the owner of Shobdo-Online.com Web Portal is NOT responsible for any kind of loss of the user by using the information posted on this website.</li>
	<li>The owner of Shobdo-Online.com Web Portal is NOT responsible if there is any change in the information posted through the advertisements of this webpage.</li>
	<li>The videos/photos posted on the Internet by the owner and/or the editor of Shobdo-Online.com Web Portal are taken and/or created after obtaining permission of the organizers or on the request of the organizers. If someone feels offended by any video/photo, the owner sincerely apologizes to the person concerned and requests the person concerned to contact the owner/editor about the video/photo.</li>
	<li>The owner is not responsible for the products and/or services of the advertisements placed in Shobdo-Online.com Web Portal.</li>
	<li>Finally, the owner is not responsible for any damages not mentioned here.</li>
	<li>You agree to indemnify and hold Shobdo-Online.com and its subsidiaries, affiliates, officers, agents, employees, partners and licensors harmless from any and all claims, losses, obligations, damages, liabilities, costs or debt and expenses (including attorney's fees) arising out of (i) your use or misuse of the Service; (ii) your Shobdo-Online.com or other Content; (iii) your violation of this Terms Of Service; (iv) your violation of the rights of any other person or entity, including claims that any Content infringes or violates any third party intellectual property rights; and (v) your breach of the foregoing representations, warranties, and covenants.</li>
	<li>This disclaimer is valid for the domain Shobdo-Online.com and for all subdomains under Shobdo-Online.com.</li>
</ol>
<br />
	<p>Please report any violations of the Terms Of Service immediately via email us at <a href="maito:info@shobdo-online.com">info@shobdo-online.com</a>.</p>

<?php
include "include/rightbar.php";
include "include/footer.php";
?>